language: php

php:
  - 5.6
  - 7

install:
  - composer self-update
  - composer install --dev --no-interaction

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: phpunit --tap --coverage-clover build/logs/clover.xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
